parameters:
  app.name: '%env(string:default:app.name_default:APP_NAME)%'
  app.name_default: 'Member Directory'
  app.logo: '%env(APP_LOGO)%'
  app.email.to: '%env(string:default:app.email.to_default:APP_EMAIL_TO)%'
  app.email.to_default: 'user@example.com'
  app.email.from: '%env(string:default:app.email.to_default:APP_EMAIL_FROM)%'
  app.email.from_default: 'user@example.com'
  app.voicemail.message: '%env(string:default:app.voicemail.message_default:APP_VOICEMAIL_MESSAGE)%'
  app.voicemail.message_default: 'Please leave a message after the tone.'
  app.voicemail.voice: '%env(string:default:app.voicemail.voice_default:APP_VOICEMAIL_VOICE)%'
  app.voicemail.voice_default: 'female'
  app.voicemail.language: '%env(string:default:app.voicemail.language_default:APP_VOICEMAIL_LANGUAGE)%'
  app.voicemail.language_default: 'en'
