# Configuration used by Whiskey Disk (https://github.com/flogic/whiskey_disk)
# to deploy code to your server.
#
# Example:
#   wd deploy --to=production
#
production:
  domain: "deploy_user@yourserver.example.com"
  deploy_to: "/path/to/member-directory"
  repository: "git@github.com:/stephenyeargin/member-directory.git"
  branch: "master"
  post_deploy_script: "config/post_deploy.sh"
  
