production:
  domain: "deploy@utmsigep.org"
  deploy_to: "/sites/chapterportal"
  repository: "git@github.com:/stephenyeargin/chapterportal.git"
  branch: "master"
  post_deploy_script: "config/post_deploy.sh"
  
